// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwwifmanoyvxffowbogw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3d2lmbWFub3l2eGZmb3dib2d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3ODAzODYsImV4cCI6MjA1NzM1NjM4Nn0.6RgEsqYrtx2NZEilMx7YMQE4O6jNa4dZVJLv70wO2sE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);